### ISSUE TITLE
Future of Castle.Zmq

### ISSUE THREAD

**Issue by jonorossi** [castleproject/castlezmq#11]
@hammett and others, this project hasn't had a commit since 16 Jun 2015. What is the current state and are people using it?

Would be good to see someone step forward if people are using it, otherwise I'll move it to https://github.com/castleproject-deprecated until we get a maintainer.

/cc @davidshen84

**Comment by hammett** [comment]
we still use it, but we have our own fork, so feel free to move it.

**Comment by jonorossi** [comment]
> we have our own fork

@hammett I assume that fork is private, not something we could point users to?

**Comment by hammett** [comment]
I’m not sure. But I also don’t want to point people there coz I have no interest in maintaining it. I’m less and less involved with .net in general.

**Comment by jonorossi** [comment]
> I’m not sure. But I also don’t want to point people there coz I have no interest in maintaining it. I’m less and less involved with .net in general.

No problem, thanks for the quick response.

**Comment by jonorossi** [comment]
If no one has stepped forward by this Friday to take over as a maintainer of this project, I'm moving it to our deprecated GitHub organisation.

**Comment by jonorossi** [comment]
This repo now lives at https://github.com/castleproject-deprecated/castlezmq. You are obviously still free to use the source code under the applicable license.
